mattermost-helm/charts/mattermost-app/templates/config.json, mattermost-helm/charts/mattermost-app/templates/deployment.yaml, mattermost-helm/charts/mattermost-elasticsearch/.helmignore, mattermost-helm/charts/mattermost-elasticsearch/Chart.yaml, mattermost-helm/charts/mattermost-elasticsearch/templates/_helpers.tpl, mattermost-helm/charts/mattermost-elasticsearch/templates/client.yaml, mattermost-helm/charts/mattermost-elasticsearch/templates/data.yaml, mattermost-helm/charts/mattermost-elasticsearch/templates/discovery-svc.yaml, mattermost-helm/charts/mattermost-elasticsearch/templates/master.yaml, mattermost-helm/charts/mattermost-elasticsearch/templates/service.yaml, mattermost-helm/charts/mattermost-elasticsearch/values.yaml, mattermost-helm/values.yaml
Add Elasticsearch to Mattermost Kubernetes.
https://mattermost.atlassian.net/browse/PLT-6985
This more-or-less works, but has definite room for improvement.
Major Known Issues:
* Elasticsearch does not use a Persistent Volume Claim, so no data is
stored persistently.
* If the Elasticsearch pods come up after the App Server pods, the app
server has already failed to connect to them, so assumes Elasticsearch
is disabled. Workaround is to kill the App Server pods so they get
restarted. Proper fix would be some kind of probe that checks they are
up similar to the one for the database.
=> PLT-6985: Add Elasticsearch to Mattermost Kubernetes.

mattermost-helm/charts/mattermost-app/templates/deployment.yaml
@coreyhulen this should fix the loadtests! Makes it Kubes 1.4 compatible.
=> Make Elasticsearch changes compatible with Kubernetes 1.5

.gitignore
There was a lot of things without any relation with the mattermost-kubernetes
project, generating some weird cases like config.json file was in the list of
ignored files for this repo.
=> Cleaning up .gitignore

docker/app/Dockerfile
Working directory needs to be the top-level MM directory or plugins have an issue finding the directories they use.
=> Fix working directory for plugins

docker/loadtest/Dockerfile
This means that to run the load tests you must manually go into the pods and run `loadtest all`, or use the ltops tool when my changes for that are ready. This is to make it easier to run multiple load tests from the same helm release, without having to tear it all down or delete all the load test pods. It also allows for configuration before the load tests run on the containers.
=> Do not run loadtest automatically when starting container

mattermost-helm/charts/mattermost-app/templates/deployment.yaml, mattermost-helm/charts/mattermost-app/templates/secret-license.yaml, mattermost-helm/charts/mattermost-loadtest/templates/job.yaml
The load test chart was trying to use the secret named "mattermost-loadtest-<release>-mattermost-license".
=> Fix license for load test chart

mattermost-helm/charts/mattermost-app/templates/deployment.yaml
- Since k8s 1.6 we can use the section initContainer and then we have logs for that.
- adding readinessProbe to make sure we only start the app pods when it everything is ready
=> moving to initContainer spec and add readinessProbe to make sure

Makefile, mattermost-helm/requirements.lock, mattermost-helm/requirements.yaml, mattermost-helm/values.yaml
Temporarily hosting the mysqlha chart at https://releases.mattermost.com/helm/mysqlha until our patch is accepted upstream and released.
=> Point mysqlha at temporary chart and configure mysql slaves for faster replication

mattermost-helm/Chart.yaml, mattermost-helm/templates/config.tpl, mattermost-helm/templates/statefull-mattermost-app.yaml, mattermost-helm/templates/tests/mattermost-app-test.yaml, mattermost-helm/values.yaml
using the mattermost-docker image as base image
- building in jenkins the image and pushing to mattermost/mattermost-enterprise-edition docker hub
- all previous images was removed.
images with tag: 5.3.1 and latest are using the mattermost-docker dockerfile
--
Changes in the helm chart:
- set the owner of the folders
- remove lost+found
- small tweaks
=> using the mattermost-docker image

docker/push-proxy/Dockerfile
> MM-13091 Review, improve and test the push proxy docker image
- Current Dockerfile follows best practises
- Ιmpovements made include:
- Change of PP_VERSION variable to APP_VERSION 
- Combining of all Docker Volume creation entries in a single entry, 
- Move of ENTRYPOINT entry to the end of the Dockerfile to follow Dockerfile best practises.
- The docker image was recreated and tested to make sure the server works as expected.
Fixes https://github.com/mattermost/mattermost-server/issues/10314
=> MM-13091 Review, improve and test the push proxy docker image

README.md
It's not very helpful to have minikube included and just makes the setup instructions seem more confusing.
=> Remove minikube from install instructions

README.md
Proposed edits to PR #68
1 - Use `mattermost.example.com` as the host/domain, consistent with TE Helm Chart configuration doc https://github.com/helm/charts/tree/master/stable/mattermost-team-edition#example-configuration
2 - Due to the Markdown heading formatting, it was hard to read through and understand if one was still part of "Configuration" or was already a new section within the guide. Propose we numbers for the sections to help guide through the set up.
This also helps with linking to specific sections of the doc, given "Ingress" is a section heading twice (once for a prerequisite, once for a configuration)
I'm 3/5 on making the sections and linking more clear, 1/5 on proposed approach.
3 - Other minor suggestions to grammar and wording.
----
Questions:
4 - Is there value adding …
=> Proposed edits to PR #68

tests/e2e-kind.sh, tests/local-path-provisioner.yaml
Update Kind version and local path provisioner
with the new kind we don't need to check if the cluster is ready, when we add the wait flag it will return when the cluster is ready
=> Update kind and local path provisioner

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/configmap-mattermost-push-proxy.yaml, charts/mattermost-push-proxy/templates/deployment.yaml, charts/mattermost-push-proxy/templates/push-config.tpl
Making changes to mattermost push proxy to enable metrics, fix of mount volumes
These changes were needed for the deployment of the push-proxy helm chart in k8s cluster.
=> Making changes to mattermost push proxy to enable metrics, fix of mount volumes

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml
This adds a checksum annotation to the jobserver pod which forces a
deployment of the jobserver on a helm upgrade
=> Add config checksum to jobserver pod

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/templates/deployment.yaml
This is a critical bugfix, without which it's not possible to deploy with customs *data* and *plugins* PVC.
The variable of *data* PVC claimName was used for the *plugins* PVC claimName, which causes error like : `Unable to mount volumes for pod XXX: timeout expired waiting for volumes to attach or mount for pod`.
Result of a `kubectl describe XXX` :
```
Volumes:
[...]
mattermost-data:
Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName:  NAME_OF_THE_DATA_PVC
ReadOnly:   false
mattermost-plugins:
Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName:  NAME_OF_THE_DATA_PVC
ReadOnly:   false
```
=> Fix claimName of existing mattermost-plugins PVC

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/README.md, charts/mattermost-team-edition/templates/ingress.yaml
Relates to https://github.com/mattermost/mattermost-server/issues/13227
This PR only address the `mattermost-team-edition`
- Updates Ingress `apiVersion` from `extensions/v1beta1` to `networking.k8s.io/v1beta1`  based on [kubernetes/kubernetes/pull/70672](https://github.com/kubernetes/kubernetes/pull/70672)
- After change bumps minimal required Kubernetes version to `1.14+`
- Fixes syntax highlighting in `README.md` markdown.
- Add *Local development* section to readme, which might help people developing locally. This can be removed if is not necessary.
- Support new versions of Kubernetes
The PR code was tested on k8 versions: 
- `1.15.2`
- `1.16.2`
I've didn't change comment  `volume.beta.kubernetes.io/storage-class` in 
https://github.com/bpietraga/mattermost-helm/blob/support_kubernete …
=> MM-20705 Support Kubernetes version 1.16 in mattermost-team-edition

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/_helpers.tpl, charts/mattermost-push-proxy/templates/ingress.yaml
Originally in #126 there was an attempt to change the chart to consider deprecated Kubernetes API (namely in 1.16) this PR is to complete that. Instead of completely drop the support for older API version this PR reads the Kubernetes Version from Helm's `Capabilities` built-in objects and executes `semverCompare` against the underlying K8s version and known version in which given API was deprecated.
enterprise-edition: #134 
team-edition: #132 
Relates to #126 and mattermost/mattermost-server#13227
=> MM-20705 Use correct apiVersion based on K8s version in mattermost-push-proxy

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/_helpers.tpl, charts/mattermost-enterprise-edition/templates/ingress-mattermost-app.yaml
Originally in #126 there was an attempt to change the chart to consider deprecated Kubernetes API (namely in 1.16) this PR is to complete that. Instead of completely drop the support for older API version this PR reads the Kubernetes Version from Helm's `Capabilities` built-in objects and executes `semverCompare` against the underlying K8s version and known version in which given API was deprecated.
push-proxy: #133 
team-edition: #132 
Relates to #126 and mattermost/mattermost-server#13227
=> MM-20705 Use correct apiVersion based on K8s version in mattermost-enterprise-edition

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/values.yaml
Fixes the extraction and removal of downloaded Plugin archives in the `extraInitContainers` section of the **Mattermost Enterprise** Helm chart.
Before, it tried to extract and remove the whole plugin URL - now it extracts the filename of the URL and uses only this part.
=> FIX: plugins tar and rm expression

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/requirements.lock, charts/mattermost-enterprise-edition/requirements.yaml, charts/mattermost-enterprise-edition/templates/tests/mattermost-app-config-test.yaml, charts/mattermost-enterprise-edition/templates/tests/mattermost-app-test.yaml, charts/mattermost-enterprise-edition/values.yaml
update mm ee to use 5.23.1
and also the dependencies because the current ones does not work in clusters >1.15
=> Bump mm ee to 5.23.1 and dependecies updates

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
This PR sets the `DriverName` to `amazons3`. It means that Mattermost will be able to use MinIO storage when `minio.enabled` is set to `true` in values.
Fixes https://github.com/mattermost/mattermost-helm/issues/162
=> [GH-162] Added required ENV vars to use MinIO storage when enabled in values

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/README.md, charts/mattermost-team-edition/templates/NOTES.txt, charts/mattermost-team-edition/templates/service.yaml, charts/mattermost-team-edition/values.yaml
Signed-off-by: Dennis Zhang <dennis.zhang.nrg@gmail.com>
I'd like for this helm chart to support loadbalancerIP for use with external loadbalancers in the cloud or MetalLB on baremetal.
Thanks.
Notes outputs:
With loadbalancerIP specified while using service type LoadBalancer example:
```
Mattermost will be available at:
192.168.1.56:80
```
Without loadbalancerIP specified while using service type LoadBalancer example:
```
You can connect to Mattermost by using the IP printed by this commmand on port 80:
MATTERMOST_IP=`kubectl get --namespace mattermost service mattermost-team-edition -o jsonpath='{.status.loadBalancer.ingress[0].ip}'`
echo $MATTERMOST_IP
```
Running the printed command:
```
$   MATTERMOST_IP=`kubectl get --namespace mattermost service mattermost-team-edition -o …
```
=> support loadbalancerIP in Team edition

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml, charts/mattermost-enterprise-edition/templates/secret-mattermost-dbsecret.yaml
=> Change mm_config to be created as a secret and mounted

.circleci/config.yml, .circleci/install_tools.sh, .gitignore, charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/README.md, charts/mattermost-enterprise-edition/ci/init-container-values.yaml, charts/mattermost-enterprise-edition/requirements.lock, charts/mattermost-enterprise-edition/requirements.yaml, charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/README.md, charts/mattermost-team-edition/Chart.yaml, tests/ct.yaml, tests/e2e-kind.sh, tests/kind-config.yaml
Update `helmpack/chart-testing` image to `v3.3.1` and fix linting issues due to upgrade of the image and the fact that Helm 2 is deprecated in the process.
=> Upgrade helm and chart-testing to latest and fix e2e issues

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-loadtest.yaml, charts/mattermost-enterprise-edition/values.yaml, charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/templates/deployment.yaml, charts/mattermost-team-edition/values.yaml
Adding support to specify nodeSelector, affinity and tolerations for deployments/pods.
N/A
=> Add nodeSelector support for helm chart

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/templates/ingress.yaml
=> Update ingress template to allow quoted hostnames/wildcards

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/OWNERS, charts/mattermost-team-edition/README.md, charts/mattermost-team-edition/requirements.lock, charts/mattermost-team-edition/requirements.yaml, tests/ct.yaml
Helm 2 is deprecated, and we should not support more this version, at this stage whoever is using it should have already migrated from v2 to v3.
This PR update the chart to the helm v3 way 😄 
- Remove the owners names, because this was set up when this chart was in the helm/charts repo, not needed here for now
- update the dependencies file to the helm v3 pattern
- update the ct config to ignore the maintainers in the chart.yaml file
- bump MM-TE to the latest version
tested with a previous chart version and upgraded to these changes and no issues found during the upgrade.
after this will do the  same for the other charts too
cc @stylianosrigas @khos2ow @angeloskyratzakos 
NONE
=> Upgrade MM-TE to be helm v3 fully compatible

README.md, charts/mattermost-operator/.helmignore, charts/mattermost-operator/Chart.yaml, charts/mattermost-operator/README.md, charts/mattermost-operator/crds/crd-clusterinstallations.yaml, charts/mattermost-operator/crds/crd-mattermostrestoredbs.yaml, charts/mattermost-operator/crds/crd-mattermosts.yaml, charts/mattermost-operator/crds/crd-minioinstances.yaml, charts/mattermost-operator/crds/crd-mysqlbackups.yaml, charts/mattermost-operator/crds/crd-mysqlclusters.yaml, charts/mattermost-operator/templates/_helpers.tpl, charts/mattermost-operator/templates/mattermost-operator/clusterrole.yaml, charts/mattermost-operator/templates/mattermost-operator/clusterrolebinding.yaml, charts/mattermost-operator/templates/mattermost-operator/deployment.yaml, charts/mattermost-operator/templates/mattermost-operator/serviceaccount.yaml, charts/mattermost-operator/templates/minio-operator/clusterrole.yaml, charts/mattermost-operator/templates/minio-operator/clusterrolebinding.yaml, charts/mattermost-operator/templates/minio-operator/deployment.yaml, charts/mattermost-operator/templates/minio-operator/namespace.yaml, charts/mattermost-operator/templates/minio-operator/serviceaccount.yaml, charts/mattermost-operator/templates/mysql-operator/clusterrole.yaml, charts/mattermost-operator/templates/mysql-operator/clusterrolebinding.yaml, charts/mattermost-operator/templates/mysql-operator/configmap.yaml, charts/mattermost-operator/templates/mysql-operator/namespace.yaml, charts/mattermost-operator/templates/mysql-operator/secret.yaml, charts/mattermost-operator/templates/mysql-operator/service.yaml, charts/mattermost-operator/templates/mysql-operator/serviceaccount.yaml, charts/mattermost-operator/templates/mysql-operator/statefulset.yaml, charts/mattermost-operator/values.yaml
- Add support for Mattermost Operator deployment via Helm chart
This PR adds a Helm chart for the Mattermost Operator, with the purpose to make Mattermost deployments faster and easier.
=> Add support for Mattermost Operator deployment via Helm chart

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml, charts/mattermost-enterprise-edition/values.yaml
All credit goes to @mrparkers 
This PR adds changes from #208 to enterprise-edition chart only. Copy-pasting the relevant PR description from #208 below.
----
This PR allows users to configure the application pod's security context, which is required in order to persist changes to the filesystem for plugins and user data.
Fixes #203
=> Add securityContext for enterprise-edition chart

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/templates/deployment.yaml, charts/mattermost-team-edition/values.yaml
Helm Upgrade might fail with `RollingUpdate` if the new pod gets into another node, introduce new config called  `deploymentStrategy` to enable customization while keeping full Backwards Compability
=> Deployment Strategy

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/README.md, charts/mattermost-team-edition/templates/deployment.yaml, charts/mattermost-team-edition/templates/service-account.yaml, charts/mattermost-team-edition/values.yaml
The mattermost team chart does not allow to specify a service account
which makes impossible to use s3 with the IAM role on the service
account.
Also added the securityContext block since it may be required on EKS
prior to 1.19
(https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#pod-configuration)
Fixes https://github.com/mattermost/mattermost-helm/issues/239
=> [GH-239] Add support for service account and security context in teams chart

tests/e2e-kind.sh, tests/kind-config.yaml
ci: update kind and k8s cluster to use 1.20.X
=> ci: update kind and k8s cluster to use 1.20.X

charts/mattermost-chaos-engine/.helmignore, charts/mattermost-chaos-engine/Chart.yaml, charts/mattermost-chaos-engine/templates/NOTES.txt, charts/mattermost-chaos-engine/templates/_helpers.tpl, charts/mattermost-chaos-engine/templates/deployment.yaml, charts/mattermost-chaos-engine/templates/ingress.yaml, charts/mattermost-chaos-engine/templates/service.yaml, charts/mattermost-chaos-engine/templates/serviceaccount.yaml, charts/mattermost-chaos-engine/templates/tests/test-connection.yaml, charts/mattermost-chaos-engine/values.yaml
Chaos Engine is a Mattermost Application which is used to create gamedayys tight coupled with
Mattermost as collaboration tool. Helm chart will help deploy in a kubernetes cluster.
Ticket: https://mattermost.atlassian.net/browse/MM-38883
=> Add a helm chart for Chaos Engine Mattermost application

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/README.md
Cert-manager docs link was outdated; this PR replaces it with an up-to-date one
=> Fix cert-manager documentation link

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml, charts/mattermost-enterprise-edition/values.yaml
This PR adds `extraEnv` array to the jobserver configuration in order to set various environment variables for mattermost.
In short, when using an external postgres, with `driverName: postgres`, you can leave datasource as an empty string, and use `extraEnv` to pass [libpq environment variables](https://www.postgresql.org/docs/current/libpq-envars.html) to the mattermost process.  Some of these can be pulled from secrets.
This PR partially addresses [#140](https://github.com/mattermost/mattermost-helm/issues/140), when using an external postgresql database.
When using mattermost paired with [Postgres Operator](https://postgres-operator.readthedocs.io/en/latest/)
```yaml
extraEnv:
- name: PGHOST
value: mattermost-database.mattermost.svc.cluster.local
- name: PGPORT
value: "5432"
- name: …
```
=> add extraEnv to jobserver values for libpq PG* variables

charts/mattermost-operator/Chart.yaml, charts/mattermost-operator/templates/mattermost-operator/deployment.yaml, charts/mattermost-operator/templates/minio-operator/deployment.yaml, charts/mattermost-operator/templates/mysql-operator/statefulset.yaml
Currently, the Chart version is passed to the value of one of the selector labels.
The selector, however, is immutable therefore any bump to the chart version makes it impossible to upgrade the chart with `helm upgrade`.
This PR removes the` helm.sh/chart` label from selector to fix this issue.
https://mattermost.atlassian.net/browse/MM-41087
=> Do not pass Chart version to deployment selectors

charts/mattermost-operator/Chart.yaml, charts/mattermost-operator/crds/crd-mattermosts.yaml, charts/mattermost-operator/templates/minio-operator/crd-minioinstances.yaml, charts/mattermost-operator/templates/minio-operator/namespace.yaml, charts/mattermost-operator/templates/mysql-operator/crd-mysqlbackups.yaml, charts/mattermost-operator/templates/mysql-operator/crd-mysqlclusters.yaml, charts/mattermost-operator/templates/mysql-operator/namespace.yaml, charts/mattermost-operator/values.yaml
This PR updates chart of Mattermost Operator.
It also removes hooks from Minio and MySQL CRDs as this breaks upgrades when Minio/MySQL are enabled.
=> Update Operator Helm chart, fix upgrade issues

charts/focalboard/Chart.yaml, charts/focalboard/templates/ingress.yaml, charts/mattermost-chaos-engine/Chart.yaml, charts/mattermost-chaos-engine/templates/ingress.yaml, charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/charts/mattermost-grafana/templates/ingress.yaml, charts/mattermost-enterprise-edition/templates/_helpers.tpl, charts/mattermost-enterprise-edition/templates/ingress-mattermost-app.yaml, charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/_helpers.tpl, charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/templates/_helpers.tpl, charts/mattermost-team-edition/templates/ingress.yaml
This PR adds support for [networking.k8s.io/v1](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122) Ingress objects while retaining support for unserved `networking.k8s.io/v1beta1` and `extensions/v1beta1` Ingress objects as well.
Out of neccessity, it also adds support for Helm v3 while retaining support for Helm v2. While [Helm v2 does support](https://v2.helm.sh/docs/chart_template_guide/#built-in-objects) the `.Capabilities.KubeVersion.GitVersion` object, [Helm v3 does not support it](https://v2.helm.sh/docs/chart_template_guide/#built-in-objects), and only supports `.Capabilities.KubeVersion.Version`. Rather sifting through Helm versions and Kubernetes versions to identify support, supported API versions are validated using `.Capabilities.APIVersions.Has` …
=> [GH-280] Add support for networking.k8s.io/v1 ingress

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/values.yaml
Issue: DOPS-936
Summary
Bump team edition helm chart to v6.6.0
Ticket Link
https://mattermost.atlassian.net/browse/DOPS-936
=> Bump team edition helm chart to v6.6.0

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/values.yaml
Issue: DOPS-936
Summary
Bump enterprise helm chart to v6.6.0
Ticket Link
https://mattermost.atlassian.net/browse/DOPS-936
=> Bump enterprise helm chart to v6.6.0 

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/values.yaml
Summary
Bump version for Mattermost Enterprise to 6.6.1
Ticket Link
Ticket: https://mattermost.atlassian.net/browse/DOPS-763
=> Bump mattermost enterprise version to 6.6.1

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/values.yaml
Summary
Bump version for Mattermost Team to 6.6.1
Ticket Link
Ticket: https://mattermost.atlassian.net/browse/DOPS-978
=> Bump Mattermost Team Edition Version to 6.6.1

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml
Fixing an issue where resulting intention would be wrong on `jobserver.extraEnv`.   
Problem is that all lines before have `-` which results in the first line of `extraEnv` is moved behind `MM_CONFIG.valueFrom.secretKeyRef.key`, resulting in a yaml error. Using `nintend` fixes this issue.
=> fix: using nintend for extraEnvs on JobServer

.circleci/config.yml, .github/workflows/pull-request.yml, .gitignore, Makefile, README.md, tests/e2e-kind.sh
We will move CircleCI pipelines to Github Actions to fix race condition. Since we stop supporting CircleCI, we are migrating existing pipelines to Github Actions.
This PR contains migration of pull request pipelines, after having stable pipelines here, we will migrate release pipelines and fix race condition at followup PR.
https://mattermost.atlassian.net/browse/CLD-3709
=> Migrate CircleCI PR pipelines to Github Actions.

README.md
We forgot to replace CircleCI Pipeline Badge to Github Pipeline Badge. PR contains changes to fix that badge.
=> Fix Pipeline Status Badge for Github

tests/ct.yaml, tests/e2e-kind.sh
Since we choose to run the `chart-testing/ct` container, as a non privileged user, we rewrite Helm's repository-config and repository-cache directories, to a non root owned directory. 
This fixes errors such as:
```
Error: Error installing charts: Error adding repo: incubator=https://charts.helm.sh/incubator: Error waiting for process: exit status 1
Error installing charts: Error adding repo: incubator=https://charts.helm.sh/incubator: Error waiting for process: exit status 1
```
https://github.com/mattermost/mattermost-helm/pull/370#issuecomment-1274400372
We also fix, a problem exposing kind's `kubeconfig` to the CT container, and an `entrypoint` typo argument. 
Ticket: https://mattermost.atlassian.net/browse/CLD-4282
=> [fix] Tests

charts/mattermost-operator/Chart.yaml, charts/mattermost-operator/templates/mattermost-operator/mattermost.yaml, charts/mattermost-operator/values.yaml, tests/e2e-kind.sh
This adds the option to enable the user the installation of the mattermost CR. instead of looking for examples at the operator
also provided link where the user can view the full spec to take example
=> add installation config of CR, provide examples

scripts/release.sh
When we added the flag `--skip-existing` the `update_index` started failing as there are no changes in the `index.yaml` if there is no release in practice by any helm.
Ticket: https://mattermost.atlassian.net/browse/CLD-4194
=> Fix update index function to skip if there is no release

charts/mattermost-operator/Chart.yaml, charts/mattermost-operator/README.md
While exploring the documentation for deploying the operator, I noticed that there is a broken URL in its readme that we can fix.
=> Readme: Fix broken URL to values.yaml

.github/workflows/pull-request.yml
This change updates some github action imports and runs the normal CI/CD checks on the master branch.
=> Run CI/CD on master branch

charts/mattermost-operator/Chart.yaml, charts/mattermost-operator/values.yaml
Operator updated to v1.20.1
Optional Mattermost deployment version updated to v7.10.2
=> Bump Operator and Mattermost default versions

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/templates/deployment.yaml, charts/mattermost-team-edition/values.yaml
Added startupProbe 
- to increase start speed up.
- best practice
- some migrations can takes a long time and initialDelaySeconds=90 for livenessProbe maybe a little.
=> Added startupProbe

charts/mattermost-rtcd/Chart.yaml, charts/mattermost-rtcd/templates/daemonset.yaml, charts/mattermost-rtcd/templates/deployment.yaml, charts/mattermost-rtcd/templates/service.yaml, charts/mattermost-rtcd/values.yaml
We are introducing support for TCP candidates for calls in https://github.com/mattermost/rtcd/pull/103. This means that if no UDP connection is possible, a TCP channel can be used instead as a backup option. The big advantage of this approach is that it can avoid having to deploy and maintain a separate TURN server to guarantee connectivity for clients unable to use UDP for whatever reason (e.g. protocol blocked by firewall).
I am updating the helm chart to reflect the changes although I couldn't really understand whether most of these are actually used/needed given we use host networking. Looking for SREs input on this.
https://mattermost.atlassian.net/browse/MM-53140
=> [MM-53140] Allow TCP connectivity for Calls

charts/mattermost-calls-offloader/Chart.yaml, charts/mattermost-calls-offloader/values.yaml
As per related PR, starting in the next version we'll be able to configure a retention time for failed jobs through the `JOBS_FAILEDJOBSRETENTIONTIME` env variable which controls the [`TTLSecondsAfterFinished`](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) value of the kubernetes job spec. This should finally remove the need to manually delete every failed recording jobs.
https://github.com/mattermost/calls-offloader/pull/43
https://mattermost.atlassian.net/browse/MM-49202
=> [MM-49202] Add retention time for failed calls-offloader jobs

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-hpa.yaml
`autoscaling/v2beta1` is not longer supported in K8S >= 1.25
=> fix: k8s > 1.24 do not support autoscaling/v2beta1

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/service.yaml, charts/mattermost-push-proxy/values.yaml
This enhancement provides optional support for push-proxy chart, Service annotations.
This can be particularly useful in scenarios where `service.type: LoadBalancer` is utilized instead of Ingress, allowing users to configure custom annotations for additional LoadBalancer setup
Ticket: https://mattermost.atlassian.net/browse/CLD-6577
=> [CLD-6577] Push proxy support service annotations

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/service.yaml, charts/mattermost-push-proxy/values.yaml
Revisiting `service` templating for the push-proxy chart.
When service.type is set to `LoadBalancer`, optionally exposing ports HTTP (80) and HTTPS (443).
This is particularly beneficial in situations where `service.type` is set to `LoadBalancer` instead of `ClusterIP` and/or using Ingress
Service Manifest continues to render as expected 
```
> helm template charts/mattermost-push-proxy 
[...]
apiVersion: v1
kind: Service
metadata:
name: release-name-mattermost-push-proxy
labels:
app.kubernetes.io/name: mattermost-push-proxy
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
helm.sh/chart:  mattermost-push-proxy-0.10.3
spec:
type: ClusterIP
ports:
- name: mattermost-push-proxy
port: 8066
targetPort: 8066
protocol: TCP
selector:
app.kubernetes.io/name: …
```
=> [CLD-6577] Mattermost push-proxy service templating revisit

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/ingress.yaml, charts/mattermost-push-proxy/values.yaml
This covers the case when special ingress spec is needed to manage different http paths.
For example, provides support for the following configuration:
```
- backend:
service:
name: response-403
port:
name: use-annotation
path: /metrics
pathType: Prefix
```
In which along with the following Ingress annotation and the use of AWS ALB Controller:
```
alb.ingress.kubernetes.io/actions.response-403: >
{"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"403","messageBody":"403 Not Allowed"}}
```
Will result in different handling of specific paths
The template continues to render as usual in case `customService` directive is not in use. 
Ticket: https://mattermost.atlassian.net/browse/CLD-7062
=> [CLD-7062] Push proxy chart revisit ingress spec

charts/mattermost-enterprise-edition/Chart.yaml, charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml, charts/mattermost-enterprise-edition/values.yaml
Adds the ability to specify `envFrom` on the enterprise chart, allowing for an easier setup of lots of environment variables for configuration (pulling all k/v pairs in as envs rather than having to add 1 by 1).
None opened but happy to open an issue if this warrants further discussion.
=> add support for envFrom on enterprise chart

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/service-monitor.yaml, charts/mattermost-push-proxy/values.yaml
Introducing ServiceMonitor resource values and templating. `servicemonitors.monitoring.coreos.com` CRD 
The template continues to render as usual when `metrics.enabled=false` (default) 
Ticket: https://mattermost.atlassian.net/browse/CLD-6825
=> Cld 6825 push proxy chart service monitor improvements

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/deployment.yaml, charts/mattermost-push-proxy/values.yaml
- Upgrade mattermost push proxy chart to support arm64/amd64 docker images 
- Use default .Chart.AppVersion value for image tag 
https://mattermost.atlassian.net/browse/CLD-7247
=> feat: Upgrade push proxy version and use default value from Chart.yaml

charts/mattermost-push-proxy/Chart.yaml, charts/mattermost-push-proxy/templates/deployment.yaml
Fix apple_auth_key definition in common-secret
=> Fix apple_auth_key definition in common-secret

charts/mattermost-calls-offloader/Chart.yaml, charts/mattermost-calls-offloader/templates/deployment.yaml, charts/mattermost-calls-offloader/values.yaml
Updating the `calls-offloader` chart to:
- Include the necessary environment variable needed by jobs to use persistent volumes. 
- Remove the volume mounts for the offloader service itself since it doesn't need to persist data.
- Use the [latest v0.9.0 image](https://hub.docker.com/layers/mattermost/calls-offloader/v0.9.0/images/sha256-1284ea8a453d3e447df53f304857803c20033f3f422659a6e902d320d00d5dbf)
=> Update calls-offloader chart

README.md, charts/mattermost-enterprise-edition/README.md, charts/mattermost-operator/README.md, charts/mattermost-team-edition/README.md
In an effort to streamline helm chart choice decisions, this change does the following:
- Update main repo README to suggest Operator chart and remove easy links to older charts.
- Provide callouts at the top of team and enterprise chart READMEs to suggest Operator chart usage.
- Small formatting updates.
Fixes https://mattermost.atlassian.net/browse/CLD-9041
=> CLD-9041: Update READMEs with operator recommendation

charts/mattermost-team-edition/Chart.yaml, charts/mattermost-team-edition/README.md, charts/mattermost-team-edition/templates/deployment.yaml, charts/mattermost-team-edition/values.yaml
The `containerSecurityContext` parameter enables the chart to be deployed to kubernetes clusters with hardened security policies.
Original discussion https://github.com/mattermost/mattermost-helm/pull/482
- Fixes https://github.com/mattermost/mattermost-helm/issues/315
- Closes https://github.com/mattermost/mattermost-helm/pull/482
=> Add containerSecurityContext to mattermost-team-edition chart

charts/mattermost-operator/crds/crd-clusterinstallations.yaml, charts/mattermost-operator/crds/crd-mattermostrestoredbs.yaml, charts/mattermost-operator/crds/crd-mattermosts.yaml
Modern helm has command `show crds` to get CRDs from chart without untarring etc:
```sh
helm show crds mattermost/mattermost-operator
```
It concatenates files from `crds/`, thus currently produces invalid yaml for mattermost-operator (with keys redefinition).
Helm has [a proposal](https://github.com/helm/helm/pull/12624) to forcefully add separators, but it was not accepted for more than a year at the moment and it's not clear when and if it will be.
This PR makes helm's output valid and useable
=> Add yaml document separators to CRDs to make `helm show crds` valid
