mattermost/mattermost-helm

- README.md
Add documentation for using this repository with minikube.
Resolves https://github.com/mattermost/platform/issues/6960
> PLT-7171 Documentation for using the mattermost-kubernetes repository

- mattermost-helm/charts/mattermost-elasticsearch/templates/client.yaml
- mattermost-helm/charts/mattermost-elasticsearch/templates/data.yaml
- mattermost-helm/charts/mattermost-elasticsearch/templates/ds-master.yaml
- mattermost-helm/charts/mattermost-elasticsearch/templates/master.yaml
Jira: https://mattermost.atlassian.net/browse/PLT-7389
GitHub: https://github.com/mattermost/mattermost-server/issues/7332
> [PLT-7389] Make vm.max_map_count more robust for Elasticsearch

- mattermost-helm/Chart.yaml
- mattermost-helm/charts/mattermost-elasticsearch/templates/client.yaml
- mattermost-helm/charts/mattermost-elasticsearch/templates/data.yaml
- mattermost-helm/charts/mattermost-elasticsearch/templates/master.yaml
- mattermost-helm/charts/mattermost-elasticsearch/templates/pvc.yaml
- mattermost-helm/charts/mattermost-elasticsearch/values.yaml
- mattermost-helm/values.yaml
Jira Ticket: https://mattermost.atlassian.net/browse/PLT-7388
GitHub: https://github.com/mattermost/mattermost-server/issues/7330
> [PLT-7388] Add persistent volume claims to Elasticsearch

- docker/push-proxy/Dockerfile
- mattermost-helm/charts/mattermost-app/templates/config.json
- mattermost-helm/charts/mattermost-app/values.yaml
- mattermost-helm/charts/mattermost-push-proxy/values.yaml
I also added a daily build of the push proxy docker image to this jenkins job https://build.mattermost.com/job/Mattermost%20Kubernetes/job/kubes-build-daily-docker/
> Fixes for push proxy and added HPNS setting

- mattermost-helm/charts/mattermost-app/templates/jobserver-deployment.yaml
- mattermost-helm/charts/mattermost-app/templates/service.yaml
This will fix the 502s I was seeing
https://mattermost.atlassian.net/browse/MM-10399
> Add selector to mattermost-app service so it excludes job servers

- mattermost-helm/charts/mattermost-app/templates/deployment.yaml
- mattermost-helm/charts/mattermost-app/templates/jobserver-deployment.yaml
- mattermost-helm/charts/mattermost-app/templates/secret-license.yaml
- mattermost-helm/charts/mattermost-app/values.yaml
- mattermost-helm/values.yaml
Jira: https://mattermost.atlassian.net/browse/MM-10838
Bonus point: set to use the correct docker repo :)
> fix job server to use secret instead of configmap to get the license

- mattermost-helm/Chart.yaml
- mattermost-helm/charts/mattermost-app/templates/jobserver-deployment.yaml
- mattermost-helm/requirements.lock
- mattermost-helm/requirements.yaml
- mattermost-helm/values.yaml
> add tags and small improvements

- Jenkinsfile
- mattermost-helm/values.yaml
fixes: https://mattermost.atlassian.net/browse/MM-11057
> Deploy MM Chart and apply basic tests and teardown

- mattermost-helm/values.yaml
Based on https://github.com/mattermost/mattermost-kubernetes/pull/46
> MM-11462 Fixing Minio

- README.md
- mattermost-helm/Chart.yaml
- mattermost-helm/requirements.lock
- mattermost-helm/requirements.yaml
- mattermost-helm/values.yaml
This is part of the k8s cluster configuration and the user can select
other ingress.
> remove nginx-ingress and kube-lego

- Jenkinsfile
- mattermost-helm/Chart.yaml
- mattermost-helm/charts/mattermost-push-proxy/templates/push-config.json
- mattermost-helm/requirements.lock
- mattermost-helm/requirements.yaml
- mattermost-helm/templates/config.tpl
- mattermost-helm/templates/configmap-mattermost-config.yaml
- mattermost-helm/templates/deployment-mattermost-jobserver.yaml
- mattermost-helm/templates/ingress-mattermost-app.yaml
- mattermost-helm/templates/loadtestconfig.tpl
- mattermost-helm/templates/statefull-mattermost-app.yaml
- mattermost-helm/templates/tests/mattermost-app-test.yaml
- mattermost-helm/values.yaml
jira: https://mattermost.atlassian.net/browse/MM-11906
> Load test point to ingress and other updates

- README.md
1. Remove mentions of "beta"
2. Link to blog post and GitLab helm chart docs
3. Update verbose in pre-requisites section
> README doc updates

- .circleci/config.yml
- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/ci/default-values.yaml
- charts/mattermost-enterprise-edition/ci/init-container-values.yaml
- charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
- charts/mattermost-enterprise-edition/values.yaml
- tests/e2e-kind.sh
- tests/local-path-provisioner.yaml
- Update the kind to use the newer version of the hostpath provisioner, so we can test the chart creating volumes
- fix the initContainer
> udpate e2e test to use working local storage

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/ci/init-container-values.yaml
- charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
- charts/mattermost-enterprise-edition/values.yaml
- tests/local-path-provisioner.yaml
- Adding support to user can add extra volumes
- bump the mm version
> add suport to extra volumes and also bump to the latest mm version

- README.md
- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Made some major updates to the README to make the instructions and prerequisites clearer. I ran through these steps myself with a fresh Kubernetes cluster to help me make the improvements.
Goal is to ask some help from the SAs to try these new steps out so they can better help customers who want to run in Kubernetes.
> MM-14848 Update the README and values.yaml with clearer instructions

- .circleci/config.yml
- .circleci/install_tools.sh
- .circleci/release.sh
Ticket -> https://mattermost.atlassian.net/browse/MM-14378
> MM-14378 Adding configuration to enable release of helm charts with chart-releaser

- README.md
- RELEASE.md
Ticket -> https://mattermost.atlassian.net/browse/MM-15383
> MM-15383 Adding RELEASE.md to cover the chart-releaser updates

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
update mm-ee to use 5.10.0 release
> bump mm-ee

- charts/mattermost-team-edition/.helmignore
- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/OWNERS
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/ci/default-values.yaml
- charts/mattermost-team-edition/ci/extra-values.yaml
- charts/mattermost-team-edition/requirements.lock
- charts/mattermost-team-edition/requirements.yaml
- charts/mattermost-team-edition/templates/NOTES.txt
- charts/mattermost-team-edition/templates/_deprecations.tpl
- charts/mattermost-team-edition/templates/_helpers.tpl
- charts/mattermost-team-edition/templates/_warnings.tpl
- charts/mattermost-team-edition/templates/deployment.yaml
- charts/mattermost-team-edition/templates/ingress.yaml
- charts/mattermost-team-edition/templates/pvc.yaml
- charts/mattermost-team-edition/templates/secret-config.yaml
- charts/mattermost-team-edition/templates/service.yaml
- charts/mattermost-team-edition/templates/tests/mattermost-config-test.yaml
- charts/mattermost-team-edition/templates/tests/mattermost-test.yaml
- charts/mattermost-team-edition/values.yaml
moving MM-TE to mattermost-helm and deprecate the one in the helm/charts repo
related PRs:
- https://github.com/helm/charts/pull/13540
- https://github.com/helm/hub/pull/75
> Add MM-te to mattermost-helm repo

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/templates/deployment.yaml
- charts/mattermost-team-edition/values.yaml
> Allow adding pod annotations

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/README.md
Adding the README.md for mattermost push proxy helm chart.
> MM-15647 Adding readme for mattermost push proxy helm chart

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/README.md
- charts/mattermost-enterprise-edition/values.yaml
- bump chart to use mattermost 5.11.0 version
> bump to use 5.11.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/values.yaml
- update TE to use 5.11.0 version
> bump te to use 5.11.0

- tests/e2e-kind.sh
- tests/local-path-provisioner.yaml
Reverts mattermost/mattermost-helm#94
just the kind
> Revert "update kind and ct testing tool"

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Missing settings from the **Integrations Management** section
> Add missing settings on config.json

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/README.md
- charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
- charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml
- charts/mattermost-enterprise-edition/values.yaml
Use configuration in the database
Moving the config.json to use the database. Any config you want to set when the pod is starting you can use the extraEnvVars for that
> use configuration in the database

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/requirements.lock
- charts/mattermost-team-edition/requirements.yaml
based on #115 , this update will fix mysql chart to support Kubernetes 1.16
> Update mysql to version 1.4.0

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/templates/NOTES.txt
helm install fails when service is set to loadBalancer
> fix the mattermostApp externalPort variable

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/templates/service.yaml
- charts/mattermost-team-edition/values.yaml
This PR adds loadbalancer settings to service.yaml
> Add loadbalancer settings to service.yaml

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/templates/deployment.yaml
- charts/mattermost-team-edition/values.yaml
Adds the ability to implement volumes and mounts from the values file see: https://github.com/mattermost/mattermost-helm/issues/124
Functionality was ported from the enterprise edition
Fixes https://github.com/mattermost/mattermost-helm/issues/124
> Add extraVolumes and Mounts

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/templates/route.yaml
- charts/mattermost-team-edition/values.yaml
Add Openshift route template and update values file accordingly. 
Fix `imageTag` variable for MySQL version which was misnamed from the subchart.
> Openshift route is added 🎉

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/templates/tests/mattermost-config-test.yaml
- charts/mattermost-team-edition/templates/tests/mattermost-test.yaml
- charts/mattermost-team-edition/values.yaml
Bump mm to 5.23.1 and fix the tests
> bump mm-te to 5.23.1

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
- charts/mattermost-push-proxy/templates/ingress.yaml
- charts/mattermost-push-proxy/templates/secrets.yaml
- charts/mattermost-push-proxy/templates/tests/mattermost-push-proxy-config-test.yaml
- charts/mattermost-push-proxy/templates/tests/mattermost-push-proxy-test.yaml
- charts/mattermost-push-proxy/values.yaml
bump to 5.21 and fixed some small issues
n/a
> push-proxy: bump to use the latest release 5.21

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
update chart for EE to use MM 5.24.0
> update chart for EE to use MM 5.24.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Update chart for TE to use MM 5.24
> update chart to use MM 5.24.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> bump mm TE to 5.24.1

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> bump mm EE to 5.24.1

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/values.yaml
> bump push proxy to 5.22.4

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
bump MM to 5.24.2, nothing fancy
> bump MM to 5.24.2

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> update MM to 5.25.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> update MM to 5.25.1

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Update TE chart to use MM 5.25.2
> bump MM to 5.25.2

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
update EE chart to use MM 5.25.2
> update EE chart to use MM 5.25.2

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> update MM to 5.26.0

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> update MM to 5.26.0 release

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/templates/deployment-mattermost-app.yaml
- charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml
- charts/mattermost-enterprise-edition/values.yaml
Changes the image of curl to be derived from values.yaml
Fixes https://github.com/mattermost/mattermost-helm/issues/177
> Changed curl image to values

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Update EE Chart to use MM 5.26.1
> update MM to use 5.26.1

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Update TE Chart to use MM 5.26.1
> Update TE Chart to use MM 5.26.1

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> update MM-TE to use 5.27.0

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> update MM-EE to use 5.27.0

- .circleci/config.yml
Move to use context instead of env vars directly
JIRA: https://mattermost.atlassian.net/browse/MM-28110
> Move to use context instead of env vars directly

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> Update MM-TE to version 5.28.1

- .circleci/release.sh
- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/requirements.lock
- charts/mattermost-enterprise-edition/requirements.yaml
- tests/ct.yaml
update repo location because the previous are deprecated
> update repo location

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/templates/deployment.yaml
Discussion started here  https://github.com/mattermost/mattermost-helm/issues/174
> Set RollingUpdate default for deployment

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Update MM-EE to version 5.29.0
> Update MM-EE to version 5.29.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/requirements.lock
- charts/mattermost-team-edition/requirements.yaml
- charts/mattermost-team-edition/values.yaml
> update mm-te to use 5.29.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/requirements.lock
Fix the outdated `team-edition/requirements.lock` file.
> Fix team edition requirements lock

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
[MM-EE] bump to use MM release 5.33.3
Fixes: https://github.com/mattermost/mattermost-helm/issues/214
> [MM-EE] bump to use MM release 5.33.3

- charts/focalboard/.helmignore
- charts/focalboard/Chart.yaml
- charts/focalboard/README.md
- charts/focalboard/templates/NOTES.txt
- charts/focalboard/templates/_helpers.tpl
- charts/focalboard/templates/deployment.yaml
- charts/focalboard/templates/ingress.yaml
- charts/focalboard/templates/pvc.yaml
- charts/focalboard/templates/service.yaml
- charts/focalboard/templates/serviceaccount.yaml
- charts/focalboard/templates/tests/test-connection.yaml
- charts/focalboard/values.yaml
If this commit applied, people will be able to install focalboard as a helm chart
Issue: https://github.com/mattermost/focalboard/issues/234
Adds a helm chart for focalboard
mattermost/focalboard#234
> Focalboard Helm Chart

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
EE: update MM to 5.36.1
tested in a kind cluster and works
n/a
> EE: update MM to 5.36.1

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/values.yaml
TE: update MM to 5.36.1
tested in a kind cluster and works
n/a
> TE: update MM to 5.36.1

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> default MM EE to 5.37.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/values.yaml
> default MM TE to 5.37.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/values.yaml
This fixes the upgrade guide for 5.0.0 and some documentation
Fixes #234
Fixes #231
> [MM-TE] Fix Upgrade to Chart 5

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> default MM EE to 5.38.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/README.md
- charts/mattermost-team-edition/values.yaml
> default MM TE to 5.38.0

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
- Fix the mount path for Apple and Android certificates
> Fix certificates mountpaths

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
update MM-TE chart to mm release 6
tested the upgrade from 5.38 and from 5.39
Fixes #269
> update MM-TE chart to mm release 6

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> update mm EE to 6.1.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> update mm te to 6.1.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> update mm-te to 6.2.0

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> update mm-ee to 6.2.0

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
> update mm-ee to 6.2.1

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
> update mm-te to 6.2.1

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Bump version for Mattermost Enterprise to 6.3.0
Ticket: https://mattermost.atlassian.net/browse/DOPS-763
> Update mm-ee to 6.3.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Bump version of Mattermost Team Enterprise to 6.3.0
Ticket: https://mattermost.atlassian.net/browse/DOPS-763
> Update mm-te to 6.3.0

- charts/mattermost-operator/Chart.yaml
- charts/mattermost-operator/crds/crd-clusterinstallations.yaml
- charts/mattermost-operator/crds/crd-mattermostrestoredbs.yaml
- charts/mattermost-operator/crds/crd-mattermosts.yaml
This bumps the CRD's to the latest version of the operator.
I had some missing settings and config during install of the Helm chart.
> Bump CRD's

- charts/mattermost-team-edition/Chart.yaml
Bump version of Mattermost Team to 6.3.2
https://mattermost.atlassian.net/browse/DOPS-776
> update mm-te to 6.3.2

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Bump version of Mattermost Team to 6.3.2
https://mattermost.atlassian.net/browse/DOPS-776
> update mm-te to 6.3.2 values

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Bump version of Mattermost Enterprise to 6.3.2
https://mattermost.atlassian.net/browse/DOPS-776
> update mm-ee to 6.3.2

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
https://mattermost.atlassian.net/browse/DOPS-795
> update mm-ee to 6.3.3

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
https://mattermost.atlassian.net/browse/DOPS-795
> update mm-te to 6.3.3

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Bump version of Mattermost Team Enterprise to 6.4.0
https://mattermost.atlassian.net/browse/DOPS-811
> update mm-ee version to 6.4.0

- charts/mattermost-enterprise-edition/Chart.yaml
- remove cpanato from maintainers
> remove cpanato from maintainers

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Issue: DOPS-823
Update release 6.4.1
https://mattermost.atlassian.net/browse/DOPS-823
> Update release 6.4.1

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Issue: DOPS-823
Update mattermost enterprise to 6.4.1
https://mattermost.atlassian.net/browse/DOPS-823
> Update mattermost enterprise to 6.4.1

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
- Update mm-te version to 6.4.2
> Update mm-te version to 6.4.2

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
- Update mm-ee version to 6.4.2
> Update mm-ee version to 6.4.2

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Issue: DOPS-866
Bump team edition helm chart to v6.5.0
https://mattermost.atlassian.net/browse/DOPS-866
> Bump team edition helm chart to v6.5.0

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Issue: DOPS-866
Bump enterprise helm chart to v6.5.0
https://mattermost.atlassian.net/browse/DOPS-866
> Bump enterprise helm chart to v6.5.0

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/ingress.yaml
- charts/mattermost-push-proxy/values.yaml
- Add support for ingressClass objects in Push Proxy ingress
> [MM-43015] Add support for ingressClass objects in Push Proxy ingress

- .gitignore
- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/values.yaml
Bump mattermost enterprise version to 6.7.0
Ticket: https://mattermost.atlassian.net/browse/DOPS-1007
> Bump mattermost enterprise version to 6.7.0

- charts/mattermost-team-edition/Chart.yaml
- charts/mattermost-team-edition/values.yaml
Ticket: https://mattermost.atlassian.net/browse/DOPS-1007
> Bump Mattermost Team Edition Version to 6.7.0

- charts/mattermost-rtcd/.helmignore
- charts/mattermost-rtcd/Chart.yaml
- charts/mattermost-rtcd/templates/NOTES.txt
- charts/mattermost-rtcd/templates/_helpers.tpl
- charts/mattermost-rtcd/templates/daemonset.yaml
- charts/mattermost-rtcd/templates/deployment.yaml
- charts/mattermost-rtcd/templates/ingress.yaml
- charts/mattermost-rtcd/templates/service.yaml
- charts/mattermost-rtcd/templates/serviceaccount.yaml
- charts/mattermost-rtcd/values.yaml
Create a new helm chart for deploying RTCD service
https://mattermost.atlassian.net/browse/MM-43735
> create new helm chart for deploying RTCD

- charts/mattermost-enterprise-edition/Chart.yaml
- charts/mattermost-enterprise-edition/templates/service-account.yaml
This fixes an issue with creating the service account. The current code creates `namespace:mynamespace` which leads to yaml errors
> Fix service account template

- charts/mattermost-rtcd/Chart.yaml
- charts/mattermost-rtcd/templates/deployment.yaml
- charts/mattermost-rtcd/values.yaml
Convert RTCD to deployments from Daemonsets
https://mattermost.atlassian.net/browse/CLD-5537
> Convert RTCD to deployments from Daemonsets

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
- charts/mattermost-push-proxy/templates/push-config.tpl
- charts/mattermost-push-proxy/templates/secrets.yaml
- charts/mattermost-push-proxy/values.yaml
- Add support for Apple APNS auth keys
> [CLD-5513] Add support for Apple APNS auth keys

- charts/mattermost-enterprise-edition/README.md
This pull request fixes some stuff on the mattermost-enterprise chart, mostly wrong links from deprecated operators and some configuration issues.
> docs: updates to link and enterprise fixes

- charts/mattermost-team-edition/templates/extra-deploy.yaml
- charts/mattermost-team-edition/values.yaml
To be able to add additional resources to
the release.
> Add extraDeploy to mattermost-team-edition

- charts/mattermost-calls-offloader/.helmignore
- charts/mattermost-calls-offloader/Chart.yaml
- charts/mattermost-calls-offloader/templates/NOTES.txt
- charts/mattermost-calls-offloader/templates/_helpers.tpl
- charts/mattermost-calls-offloader/templates/deployment.yaml
- charts/mattermost-calls-offloader/templates/hpa.yaml
- charts/mattermost-calls-offloader/templates/role.yaml
- charts/mattermost-calls-offloader/templates/rolebinding.yaml
- charts/mattermost-calls-offloader/templates/service.yaml
- charts/mattermost-calls-offloader/templates/serviceaccount.yaml
- charts/mattermost-calls-offloader/values.yaml
- Mattermost Calls Offloader service Helm chart
> [CLD-5982] First commit of Mattermost Calls Offloader service Helm chart

- charts/mattermost-calls-offloader/Chart.yaml
- charts/mattermost-calls-offloader/values.yaml
- Release calls offloader v0.3.1
> [CLD-6125] Release calls offloader v0.3.1

- charts/mattermost-calls-offloader/Chart.yaml
- charts/mattermost-calls-offloader/values.yaml
- Release calls-offloader v0.3.3
> CLD-6281 Release calls-offloader v0.3.3

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
- charts/mattermost-push-proxy/templates/push-config.tpl
- charts/mattermost-push-proxy/templates/secrets.yaml
- charts/mattermost-push-proxy/values.yaml
- Update Push Proxy helm chart to support new Android API for notifications
> [CLD-6350] Update Push Proxy helm chart to support new Android API for notifications

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/values.yaml
> [CLD-6675] Release push proxy 5.28.0

- charts/mattermost-calls-offloader/Chart.yaml
- charts/mattermost-calls-offloader/values.yaml
Updating `calls-offloader` to latest v0.5.0.
https://mattermost.atlassian.net/browse/CLD-6697
> [CLD-6697] Bump calls-offloader to latest

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/values.yaml
Security patch https://github.com/mattermost/mattermost-push-proxy/releases/tag/v5.29.0
Ticket: https://mattermost.atlassian.net/browse/CLD-7203
> [chore] Bumping up push-proxy version

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/values.yaml
Security patch https://github.com/mattermost/mattermost-push-proxy/releases/tag/v5.30.0
Ticket: https://mattermost.atlassian.net/browse/CLD-7219
> [chore] Bumping up push-proxy app version to v5.30.0

- charts/mattermost-push-proxy/Chart.yaml
Introducing changes here: https://github.com/mattermost/mattermost-push-proxy/pull/117
Ticket: https://mattermost.atlassian.net/browse/CLD-7354
> [chore] Updating push-proxy

- charts/mattermost-operator/Chart.yaml
- charts/mattermost-operator/crds/crd-clusterinstallations.yaml
- charts/mattermost-operator/crds/crd-mattermosts.yaml
- charts/mattermost-operator/values-with-mattermost.yaml
- charts/mattermost-operator/values.yaml
Fixes https://mattermost.atlassian.net/browse/CLD-7251
> Upgrade mattermost operator to v1.21.0

- charts/mattermost-calls-offloader/Chart.yaml
- charts/mattermost-calls-offloader/values.yaml
- Release calls-offloader 0.8.0
> [CLD-7542] Release calls-offloader 0.8.0

- charts/mattermost-push-proxy/Chart.yaml
Bump mattermost-push-proxy
https://mattermost.atlassian.net/browse/CLD-7605
> Bump mattermost-push-proxy

- charts/mattermost-operator/Chart.yaml
- charts/mattermost-operator/values-with-mattermost.yaml
- charts/mattermost-operator/values.yaml
Fixes https://mattermost.atlassian.net/browse/CLD-8027
> Update Mattermost Operator to v1.22.0

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/external_secrets.yaml
- charts/mattermost-push-proxy/templates/secrets.yaml
- charts/mattermost-push-proxy/values.yaml
Support external-secrets conditionally to push-proxy
https://mattermost.atlassian.net/browse/CLD-8017
> Support external-secrets conditionally to push-proxy

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
Refactor secrets in push-proxy
https://mattermost.atlassian.net/browse/CLD-8017
> Refactor secrets in push-proxy

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
- charts/mattermost-push-proxy/templates/external_secrets.yaml
Lint fixes in mattermost-push-proxy chart
https://mattermost.atlassian.net/browse/CLD-8015
> Lint fixes

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/external_secrets.yaml
> Fix external secret naming

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
> Fix auth key paths

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
> Remove unused mounts

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/push-config.tpl
> Fix config-template

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/push-config.tpl
> Fix config-template all cases

- charts/mattermost-push-proxy/Chart.yaml
- Bump helm chart of mattermost push proxy for version 6.2.0 
https://mattermost.atlassian.net/browse/CLD-8323
> feat: Bump push proxy chart for version 6.2.0

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
fix indentation
https://mattermost.atlassian.net/browse/CLD-8355
> fix indentation

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/deployment.yaml
Bump push-proxy to 0.13.2 - Fix typo in android settings
https://mattermost.atlassian.net/browse/CLD-8364
> Bump push-proxy to 0.13.2 - Fix typo in android settings

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/push-config.tpl
- charts/mattermost-push-proxy/values.yaml
Bump push proxy chart version.
Related thread: https://hub.mattermost.com/private-core/pl/k6cf7gk4hjff7bcks4ash1wmqw
> fet: Bump push proxy helm chart version

- .github/dependabot.yml
Add dependabot in mattermost-helm
https://mattermost.atlassian.net/browse/CLD-8888
> Add dependabot in mattermost-helm

- charts/mattermost-enterprise-edition/README.md
- charts/mattermost-team-edition/README.md
A small correction for chart links
> Fix chart links in README callout

- charts/mattermost-operator/Chart.yaml
- charts/mattermost-operator/crds/crd-clusterinstallations.yaml
- charts/mattermost-operator/crds/crd-mattermostrestoredbs.yaml
- charts/mattermost-operator/crds/crd-mattermosts.yaml
- charts/mattermost-operator/values-with-mattermost.yaml
- charts/mattermost-operator/values.yaml
This updates the chart for deploying the Mattermost Operator to version v1.23.0.
> Bump Mattermost Operator version to v1.23.0

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/ingress.yaml
- charts/mattermost-push-proxy/values.yaml
Add ingress labels to push-proxy
https://mattermost.atlassian.net/browse/CLD-9207
> Add ingress labels to push-proxy

- charts/mattermost-push-proxy/Chart.yaml
- charts/mattermost-push-proxy/templates/ingress.yaml
Fix push-proxy custom ingress labels
> Fix push-proxy custom ingress labels

- charts/mattermost-enterprise-edition/README.md
- charts/mattermost-team-edition/README.md
language to be more firm on unsupported helm charts
> Update language around helm charts
